### ISSUE TITLE
Navigation breaks when styles change

### ISSUE THREAD

**Issue by 0dp** [holger1411/understrap#391]
Hi Everyone,

Tonight I was going to start up a new project and followed the normal installation procedure.
I then ran `$gulp watch-bs` and started editing files.

The first thing I did was add a body background-color and save the file. This resulted in the files being build by the task, and when the page reloaded the navbar was broken.

Here is a screenshot of the menu after page reload (remember I've only changed the body background-color).
<img width="1630" alt="screen shot 2017-08-15 at 22 48 32" src="https://user-images.githubusercontent.com/3642367/29335739-f3ef9b96-820b-11e7-8858-3526c64d9347.png">

Here a screenshot highlighting the hamburger and the menu expanded
<img width="1680" alt="screen shot 2017-08-15 at 22 49 59" src="https://user-images.githubusercontent.com/3642367/29335787-1be7a3f0-820c-11e7-8385-1d1696e9887d.png">

I have now reproduced the issue four times, but I have a hard time to figure our where to start troubleshooting this. It has never happened before

**Comment by typeplus** [comment]
Do you have any plugins installed? Does removing the change you made to the body background-color revert the menu back to working?

**Comment by 0dp** [comment]
@typeplus It's a fresh, clean WordPress install. No plugins were installed doing this. 
Important question, Removing added styling did not revert the changes

**Comment by eberhapa** [comment]
I have the same problem. Recompiling the css with bootstrap 4 **beta** breaks the navigation.

**Comment by holger1411** [comment]
Hm, do the following:
- Delete the node_modules folder
- Delete the /src folder
- Clear your npm cache
- Then run `npm install`
- Make sure you use any file from UnderStrap 0.6.3
- Run `gulp scripts` and `gulp sass`

I encounter the same issue during the update from BS4 Alpha to beta.
The markup was changed slightly and Beta uses the popper.js script instead of tether.js anymore for popoup functionality.

If that did not help: Does your webdev tools console shows any JS errors?

**Comment by eberhapa** [comment]
Did all the steps. The issue still occurs. No js errors. I'm using understrap-child.

**Comment by holger1411** [comment]
Okay, found the problem.
The child theme removes all scripts from the parent and loads its own. Which is okay.
But due to the replacement of tether.js with popper.js the child needs to load popper.js, too.

Fixed that and released 0.3.4 here: https://github.com/holger1411/understrap-child/releases/tag/0.3.4

**Comment by eberhapa** [comment]
Still not. Popper js was loading from the parent theme before. So its not the fault of popper.

**Comment by 0dp** [comment]
@holger1411 I just tried your suggestion but it didn't do anything. popper.js is also loaded correctly.
No JS errors either

**Comment by shaunhAU** [comment]
I have been able to replicate this issue too.
1. Installed a fresh version of Understrap.
2. npm install
3. gulp copy-assets
(menu displayed find up to here.)
4. made a change to the _theme.scss and gulp minify-css ... reloaded the page and menu is broken.

**Comment by holger1411** [comment]
Strange thing, works here.
Can anyone send an URL?/Have to problem on a ive site?

**Comment by eberhapa** [comment]
Hi @holger1411. I tried a clean install and it was working. But i inspected the network tab and saw that the .min.css file from github is a not compiled version. So the .min.css includes bootstrap 4 alpha and the css file bootstrap 4 beta. When i change the file which is loaded in the functions.php from .min.css to .css, its breaking the navigation again. This is the case for understrap parent and child theme. After running gulp it also breaks.

**Comment by holger1411** [comment]
Argh, wired things happedn here...I´ve updated UnderStrap to 0.6.5 and the child theme to 0.3.5. Pls try it again with this new versions.

**Comment by eberhapa** [comment]
Nice, its working. But i still had problems after updating and recompiling. After that i copied file after file from my child theme into a new blank understrap child theme and the issue was in header.php. I have no clue why, because GIT just showed the repositioning of the button. But this change was there today in the morning :S

**Comment by ytsurk** [comment]
thanks for the update ! nav is back

**Comment by 0dp** [comment]
I can confirm that the navbar works as expected. Changing styling does not break the navigation.
Are we ready to close this issue or should I leave it open a bit?
