### ISSUE TITLE
Woocommerce Billing fields missing on Checkout

### ISSUE THREAD

**Issue by veryselfishman** [holger1411/understrap#490]
The latest inc/woocommerce.php includes an ammended function name on 36:

36  function understrap_wc_form_field_args( $args, $key, $value = null ) {

The add_filter arguments need to ammended to reference the renamed function on line 23:

28  add_filter( 'woocommerce_form_field_args', 'wc_form_field_args', 10, 3 );

Otherwise no input fields appear on the Woocommerce Checkout screen.

**Comment by holger1411** [comment]
Thx @veryselfishman for reporting.
Fixed it here:
https://github.com/holger1411/understrap/commit/86caee1f17f6e4680fedd87b592f01c02e386a9d

**Comment by holger1411** [comment]
Srry, here:
https://github.com/holger1411/understrap/commit/44c38d710a4f078d21a548b4756e38fe86dc6835

**Comment by gryffinnovak** [comment]
Still experiencing this issue, even after applying above fix. Billing and shipping input fields absent from Woocommerce checkout and account pages.

**Comment by Behan2** [comment]
Hello, I'm experiencing an issue where the billing fields on the checkout page are extremely small and un presentable. Is there anyway to stretch out the size of these fields?

**Comment by staceycordoni** [comment]
Also have this issue

**Comment by staceycordoni** [comment]
It's with stripe payment gateway specifically. Here's a screenshot:
https://d.pr/i/wmdQVt

I found a work-around, by checking off "Inline Credit Card Form" in the stripe settings, eg:
https://d.pr/i/DwyOHB

**Comment by 0dp** [comment]
I never thought of this as a theme bug(maybe it is), but I think I fixed it by giving all the fields a width of 100%

**Comment by getmehire** [comment]
On checkout phone and email, fields are not showing any idea why?
[https://ultrawave.co.il/checkout/](url)
